### ISSUE TITLE
List of node IDs

### ISSUE THREAD

**Issue by hinhthoi** [Cloudcone/cloudcone-whmcs#4]
Hi,

In the api manual, when we deploy new instance, we can specify node ID.

How can we know about the available node IDs?

Thanks!

**Comment by immdraselkhan** [comment]
Hello @hinhthoi

First of all go this link: https://app.cloudcone.com/compute

Then click manage button under your VPS: http://prntscr.com/la7dqw

Then you will redirect VPS dashboard & you will also find the Node/VPS/Server ID: http://prntscr.com/la7f1a

Let me know If you need any help.

**Comment by ghost** [comment]
> Hi,
> 
> In the api manual, when we deploy new instance, we can specify node ID.
> 
> How can we know about the available node IDs?
> 
> Thanks!

Hello @hinhthoi

First of all go this link: https://app.cloudcone.com/compute

Then click manage button under your VPS: http://prntscr.com/la7dqw

Then you will redirect VPS dashboard & you will also find the Node/VPS/Server ID: http://prntscr.com/la7f1a

Let me know If you need any help.
